/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Movimentacao;

import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import model.Client;
import model.Employee;
import model.Order;
import model.OrderItem;
import model.Product;
import service.ClientService;
import service.EmployeeService;
import service.OrderService;
import service.ProductService;
import util.Mascara;
import util.ValidaNumeros;
import static util.ValidaNumeros.nf;
import util.data;

/**
 *
 * @author Jonas Santos
 */
public class AlterarMovimento extends javax.swing.JFrame {

    /**
     * Creates new form AlteraMovimentacao
     */
    String codigo;
    List<OrderItem> listProduto;
    List<Client> listCliente;
    List<Employee> listFuncionario;
    Product servico;
    Double valorUnitario;
    Integer indice;
    String codigoAtualCliente;
    String codigoAtualFuncionario;
    List<OrderItem> listProd = new ArrayList<OrderItem>();

    public AlterarMovimento(String ID) {
        initComponents();
        codigo = ID;
        txtValorTotalVenda.setFormatterFactory(Mascara.getValorMask());
        setValue();
        TableColumnModel modeltable = grid.getColumnModel();
        modeltable.getColumn(0).setPreferredWidth(50);
        modeltable.getColumn(1).setPreferredWidth(280);
        modeltable.getColumn(2).setPreferredWidth(130);
        modeltable.getColumn(3).setPreferredWidth(100);
        modeltable.getColumn(4).setPreferredWidth(150);
        txtCodigoBusca.setDocument(new ValidaNumeros());
    }

    private AlterarMovimento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PesquisaProduto = new javax.swing.JDialog();
        lbDescricao = new javax.swing.JLabel();
        lbQtdeResult = new javax.swing.JLabel();
        btBuscar = new javax.swing.JButton();
        txtDescricao = new javax.swing.JTextField();
        lbCodigo = new javax.swing.JLabel();
        txtCodigoBusca = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        gridBusca = new javax.swing.JTable();
        btCancelar1 = new javax.swing.JButton();
        btIncluir = new javax.swing.JButton();
        lbTitulo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        IncluirProduto = new javax.swing.JDialog();
        lbCodigo1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCodigoProd = new javax.swing.JTextField();
        txtDescricaoProd = new javax.swing.JTextField();
        lbDescricao1 = new javax.swing.JLabel();
        lbQtde = new javax.swing.JLabel();
        txtQtde = new javax.swing.JTextField();
        lbValor = new javax.swing.JLabel();
        txtValorUni = new javax.swing.JFormattedTextField();
        lbTotal = new javax.swing.JLabel();
        btEfetivar = new javax.swing.JButton();
        btCancelarInc = new javax.swing.JButton();
        txtTotalProd = new javax.swing.JFormattedTextField();
        AlterarProduto = new javax.swing.JDialog();
        lbCodigo2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCodigoAltProd = new javax.swing.JTextField();
        txtDescricaoAltProd = new javax.swing.JTextField();
        lbDescricao2 = new javax.swing.JLabel();
        lbQtde1 = new javax.swing.JLabel();
        txtAltQtde = new javax.swing.JTextField();
        lbValor1 = new javax.swing.JLabel();
        txtValorUniAlt = new javax.swing.JFormattedTextField();
        lbTotal1 = new javax.swing.JLabel();
        btEfetivarAlt = new javax.swing.JButton();
        btCancelarAlt = new javax.swing.JButton();
        txtTotalProdAlt = new javax.swing.JFormattedTextField();
        PesquisarCliente = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        lbDescricao3 = new javax.swing.JLabel();
        lbQtdeResultCliente = new javax.swing.JLabel();
        lbCPF = new javax.swing.JLabel();
        btLimparBuscaCliente = new javax.swing.JButton();
        txtBuscaRGCliente = new javax.swing.JFormattedTextField();
        lbCPF1 = new javax.swing.JLabel();
        btBuscar1 = new javax.swing.JButton();
        txtBuscaNomeCliente = new javax.swing.JTextField();
        txtBuscaCPFCliente = new javax.swing.JFormattedTextField();
        lbCodigo3 = new javax.swing.JLabel();
        txtBuscaCodigoCliente = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        gridBuscaCliente = new javax.swing.JTable();
        btCancelar2 = new javax.swing.JButton();
        btBuscaEscolherCliente = new javax.swing.JButton();
        lbTitulo1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btPesquisarCliente = new javax.swing.JButton();
        cbCliente = new javax.swing.JComboBox<>();
        btCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        txtDataAlteracao = new javax.swing.JTextField();
        lbDataAlteracao = new javax.swing.JLabel();
        lbValorTotalVenda = new javax.swing.JLabel();
        txtValorTotalVenda = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        btAdicionarProd = new javax.swing.JButton();
        btRemoverProd = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btAlterar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        grid = new javax.swing.JTable();
        txtCodigoCliente = new javax.swing.JTextField();
        lbNome1 = new javax.swing.JLabel();
        cbFuncionario = new javax.swing.JComboBox<>();
        txtCodigoFuncionario = new javax.swing.JTextField();
        lbcodigo = new javax.swing.JLabel();
        cod_movimentacao = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        btSalvarMovimento = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        PesquisaProduto.setMinimumSize(new java.awt.Dimension(675, 435));
        PesquisaProduto.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbDescricao.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbDescricao.setForeground(new java.awt.Color(255, 255, 255));
        lbDescricao.setText("Descricao");
        PesquisaProduto.getContentPane().add(lbDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, -1, -1));

        lbQtdeResult.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbQtdeResult.setForeground(new java.awt.Color(255, 255, 255));
        lbQtdeResult.setText("Pesquise o produto desejado");
        PesquisaProduto.getContentPane().add(lbQtdeResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 180, 30));

        btBuscar.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        btBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/botaoefetivar5.png"))); // NOI18N
        btBuscar.setText("Buscar");
        btBuscar.setBorderPainted(false);
        btBuscar.setContentAreaFilled(false);
        btBuscar.setFocusPainted(false);
        btBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });
        PesquisaProduto.getContentPane().add(btBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 110, 40));

        txtDescricao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDescricaoFocusLost(evt);
            }
        });
        txtDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricaoActionPerformed(evt);
            }
        });
        PesquisaProduto.getContentPane().add(txtDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 190, -1));

        lbCodigo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbCodigo.setForeground(new java.awt.Color(255, 255, 255));
        lbCodigo.setText("Codigo");
        PesquisaProduto.getContentPane().add(lbCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        txtCodigoBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoBuscaActionPerformed(evt);
            }
        });
        PesquisaProduto.getContentPane().add(txtCodigoBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 170, -1));

        gridBusca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descricao", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        gridBusca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gridBuscaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(gridBusca);

        PesquisaProduto.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, 180));

        btCancelar1.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        btCancelar1.setForeground(new java.awt.Color(255, 255, 255));
        btCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/botaocancelar6.png"))); // NOI18N
        btCancelar1.setText("Cancelar");
        btCancelar1.setBorderPainted(false);
        btCancelar1.setContentAreaFilled(false);
        btCancelar1.setFocusPainted(false);
        btCancelar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelar1ActionPerformed(evt);
            }
        });
        PesquisaProduto.getContentPane().add(btCancelar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 100, 40));

        btIncluir.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        btIncluir.setForeground(new java.awt.Color(255, 255, 255));
        btIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/botaoefetivar5.png"))); // NOI18N
        btIncluir.setText("Incluir");
        btIncluir.setBorderPainted(false);
        btIncluir.setContentAreaFilled(false);
        btIncluir.setFocusPainted(false);
        btIncluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIncluirActionPerformed(evt);
            }
        });
        PesquisaProduto.getContentPane().add(btIncluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 100, 40));

        lbTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo.setText("Pesquisar Produto");
        PesquisaProduto.getContentPane().add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 640, 40));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/PainelFundo.png"))); // NOI18N
        jLabel4.setText("jLabel1");
        PesquisaProduto.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 630, 380));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/FundoTelaInicial3.jpg"))); // NOI18N
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PesquisaProduto.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 430));

        IncluirProduto.setMinimumSize(new java.awt.Dimension(435, 200));
        IncluirProduto.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbCodigo1.setText("Codigo");
        IncluirProduto.getContentPane().add(lbCodigo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 49, 40, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Incluir Produto");
        IncluirProduto.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 421, -1));

        txtCodigoProd.setEditable(false);
        txtCodigoProd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        IncluirProduto.getContentPane().add(txtCodigoProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 46, 60, -1));

        txtDescricaoProd.setEditable(false);
        txtDescricaoProd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        IncluirProduto.getContentPane().add(txtDescricaoProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 46, 200, -1));

        lbDescricao1.setText("Descrição");
        IncluirProduto.getContentPane().add(lbDescricao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 49, 60, -1));

        lbQtde.setText("Quantidade");
        IncluirProduto.getContentPane().add(lbQtde, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 87, -1, -1));

        txtQtde.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtQtde.setText("1");
        txtQtde.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtQtdeFocusLost(evt);
            }
        });
        txtQtde.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQtdeKeyPressed(evt);
            }
        });
        IncluirProduto.getContentPane().add(txtQtde, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 84, 40, -1));

        lbValor.setText("Valor");
        IncluirProduto.getContentPane().add(lbValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 87, 38, -1));

        txtValorUni.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtValorUni.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtValorUniFocusLost(evt);
            }
        });
        txtValorUni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtValorUniKeyPressed(evt);
            }
        });
        IncluirProduto.getContentPane().add(txtValorUni, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 84, 70, -1));

        lbTotal.setText("Total");
        IncluirProduto.getContentPane().add(lbTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 87, 30, -1));

        btEfetivar.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        btEfetivar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/botaoefetivar5.png"))); // NOI18N
        btEfetivar.setText("Efetivar");
        btEfetivar.setBorderPainted(false);
        btEfetivar.setContentAreaFilled(false);
        btEfetivar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btEfetivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEfetivarActionPerformed(evt);
            }
        });
        IncluirProduto.getContentPane().add(btEfetivar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 100, 40));

        btCancelarInc.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        btCancelarInc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/botaocancelar6.png"))); // NOI18N
        btCancelarInc.setText("Cancelar");
        btCancelarInc.setBorderPainted(false);
        btCancelarInc.setContentAreaFilled(false);
        btCancelarInc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCancelarInc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarIncActionPerformed(evt);
            }
        });
        IncluirProduto.getContentPane().add(btCancelarInc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 100, 40));

        txtTotalProd.setEditable(false);
        txtTotalProd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotalProd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTotalProdFocusLost(evt);
            }
        });
        IncluirProduto.getContentPane().add(txtTotalProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 84, 90, -1));

        AlterarProduto.setMinimumSize(new java.awt.Dimension(435, 200));
        AlterarProduto.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbCodigo2.setText("Codigo");
        AlterarProduto.getContentPane().add(lbCodigo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 49, 40, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Alterar Produto");
        AlterarProduto.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 421, -1));

        txtCodigoAltProd.setEditable(false);
        txtCodigoAltProd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AlterarProduto.getContentPane().add(txtCodigoAltProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 46, 60, -1));

        txtDescricaoAltProd.setEditable(false);
        txtDescricaoAltProd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AlterarProduto.getContentPane().add(txtDescricaoAltProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 46, 200, -1));

        lbDescricao2.setText("Descrição");
        AlterarProduto.getContentPane().add(lbDescricao2, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 49, 60, -1));

        lbQtde1.setText("Quantidade");
        AlterarProduto.getContentPane().add(lbQtde1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 87, -1, -1));

        txtAltQtde.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAltQtde.setText("1");
        txtAltQtde.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAltQtdeFocusLost(evt);
            }
        });
        AlterarProduto.getContentPane().add(txtAltQtde, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 84, 40, -1));

        lbValor1.setText("Valor");
        AlterarProduto.getContentPane().add(lbValor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 87, 38, -1));

        txtValorUniAlt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtValorUniAlt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtValorUniAltFocusLost(evt);
            }
        });
        AlterarProduto.getContentPane().add(txtValorUniAlt, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 84, 70, -1));

        lbTotal1.setText("Total");
        AlterarProduto.getContentPane().add(lbTotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 87, 30, -1));

        btEfetivarAlt.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        btEfetivarAlt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/botaoefetivar5.png"))); // NOI18N
        btEfetivarAlt.setText("Efetivar");
        btEfetivarAlt.setBorderPainted(false);
        btEfetivarAlt.setContentAreaFilled(false);
        btEfetivarAlt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btEfetivarAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEfetivarAltActionPerformed(evt);
            }
        });
        AlterarProduto.getContentPane().add(btEfetivarAlt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 100, 40));

        btCancelarAlt.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        btCancelarAlt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/botaocancelar6.png"))); // NOI18N
        btCancelarAlt.setText("Cancelar");
        btCancelarAlt.setBorderPainted(false);
        btCancelarAlt.setContentAreaFilled(false);
        btCancelarAlt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCancelarAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarAltActionPerformed(evt);
            }
        });
        AlterarProduto.getContentPane().add(btCancelarAlt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 100, 40));

        txtTotalProdAlt.setEditable(false);
        txtTotalProdAlt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotalProdAlt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTotalProdAltFocusLost(evt);
            }
        });
        AlterarProduto.getContentPane().add(txtTotalProdAlt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 84, 90, -1));

        PesquisarCliente.setMinimumSize(new java.awt.Dimension(666, 425));
        PesquisarCliente.setUndecorated(true);
        PesquisarCliente.setResizable(false);
        PesquisarCliente.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Filtros");
        jLabel11.setMaximumSize(new java.awt.Dimension(58, 30));
        jLabel11.setMinimumSize(new java.awt.Dimension(58, 30));
        jLabel11.setOpaque(true);
        jLabel11.setPreferredSize(new java.awt.Dimension(58, 30));
        PesquisarCliente.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 170, 40));

        lbDescricao3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbDescricao3.setForeground(new java.awt.Color(255, 255, 255));
        lbDescricao3.setText("Nome");
        PesquisarCliente.getContentPane().add(lbDescricao3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        lbQtdeResultCliente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbQtdeResultCliente.setForeground(new java.awt.Color(255, 255, 255));
        lbQtdeResultCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbQtdeResultCliente.setText("Informe o filtro desejado");
        PesquisarCliente.getContentPane().add(lbQtdeResultCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 180, 30));

        lbCPF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbCPF.setForeground(new java.awt.Color(255, 255, 255));
        lbCPF.setText("CPF");
        PesquisarCliente.getContentPane().add(lbCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        btLimparBuscaCliente.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        btLimparBuscaCliente.setForeground(new java.awt.Color(255, 255, 255));
        btLimparBuscaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/botaoefetivar5.png"))); // NOI18N
        btLimparBuscaCliente.setText("Limpar");
        btLimparBuscaCliente.setBorderPainted(false);
        btLimparBuscaCliente.setContentAreaFilled(false);
        btLimparBuscaCliente.setFocusPainted(false);
        btLimparBuscaCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btLimparBuscaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparBuscaClienteActionPerformed(evt);
            }
        });
        PesquisarCliente.getContentPane().add(btLimparBuscaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 120, 40));

        txtBuscaRGCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBuscaRGCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBuscaRGClienteFocusGained(evt);
            }
        });
        txtBuscaRGCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaRGClienteActionPerformed(evt);
            }
        });
        PesquisarCliente.getContentPane().add(txtBuscaRGCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 120, -1));

        lbCPF1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbCPF1.setForeground(new java.awt.Color(255, 255, 255));
        lbCPF1.setText("RG");
        PesquisarCliente.getContentPane().add(lbCPF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        btBuscar1.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        btBuscar1.setForeground(new java.awt.Color(255, 255, 255));
        btBuscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/botaoefetivar5.png"))); // NOI18N
        btBuscar1.setText("Buscar");
        btBuscar1.setBorderPainted(false);
        btBuscar1.setContentAreaFilled(false);
        btBuscar1.setFocusPainted(false);
        btBuscar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscar1ActionPerformed(evt);
            }
        });
        PesquisarCliente.getContentPane().add(btBuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 120, 40));

        txtBuscaNomeCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBuscaNomeClienteFocusLost(evt);
            }
        });
        txtBuscaNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaNomeClienteActionPerformed(evt);
            }
        });
        PesquisarCliente.getContentPane().add(txtBuscaNomeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 120, -1));

        txtBuscaCPFCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBuscaCPFCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBuscaCPFClienteFocusGained(evt);
            }
        });
        PesquisarCliente.getContentPane().add(txtBuscaCPFCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 120, -1));

        lbCodigo3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbCodigo3.setForeground(new java.awt.Color(255, 255, 255));
        lbCodigo3.setText("Codigo");
        PesquisarCliente.getContentPane().add(lbCodigo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        txtBuscaCodigoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaCodigoClienteActionPerformed(evt);
            }
        });
        PesquisarCliente.getContentPane().add(txtBuscaCodigoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 120, -1));

        gridBuscaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "CPF", "RG", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        gridBuscaCliente.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        gridBuscaCliente.setShowHorizontalLines(false);
        gridBuscaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gridBuscaClienteMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(gridBuscaCliente);

        PesquisarCliente.getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 430, 240));

        btCancelar2.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        btCancelar2.setForeground(new java.awt.Color(255, 255, 255));
        btCancelar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/botaocancelar6.png"))); // NOI18N
        btCancelar2.setText("Fechar");
        btCancelar2.setBorderPainted(false);
        btCancelar2.setContentAreaFilled(false);
        btCancelar2.setFocusPainted(false);
        btCancelar2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCancelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelar2ActionPerformed(evt);
            }
        });
        PesquisarCliente.getContentPane().add(btCancelar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 110, 40));

        btBuscaEscolherCliente.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        btBuscaEscolherCliente.setForeground(new java.awt.Color(255, 255, 255));
        btBuscaEscolherCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/botaoefetivar5.png"))); // NOI18N
        btBuscaEscolherCliente.setText("Escolher");
        btBuscaEscolherCliente.setBorderPainted(false);
        btBuscaEscolherCliente.setContentAreaFilled(false);
        btBuscaEscolherCliente.setFocusPainted(false);
        btBuscaEscolherCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btBuscaEscolherCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscaEscolherClienteActionPerformed(evt);
            }
        });
        PesquisarCliente.getContentPane().add(btBuscaEscolherCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 100, 40));

        lbTitulo1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbTitulo1.setForeground(new java.awt.Color(255, 255, 255));
        lbTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo1.setText("Pesquisar Cliente");
        PesquisarCliente.getContentPane().add(lbTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 390, 40));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/PainelFundo.png"))); // NOI18N
        jLabel9.setText("jLabel1");
        PesquisarCliente.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 630, 380));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/FundoTelaInicial3.jpg"))); // NOI18N
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PesquisarCliente.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 430));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btPesquisarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/lupa.png"))); // NOI18N
        btPesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btPesquisarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 169, 20, 28));

        cbCliente.setBackground(new java.awt.Color(0, 0, 0));
        cbCliente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbCliente.setForeground(new java.awt.Color(255, 255, 255));
        cbCliente.setLightWeightPopupEnabled(false);
        cbCliente.setOpaque(false);
        cbCliente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbClienteItemStateChanged(evt);
            }
        });
        cbCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbClienteFocusGained(evt);
            }
        });
        getContentPane().add(cbCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 270, -1));

        btCancelar.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/botaocancelar6.png"))); // NOI18N
        btCancelar.setText(" Cancelar");
        btCancelar.setBorder(null);
        btCancelar.setBorderPainted(false);
        btCancelar.setContentAreaFilled(false);
        btCancelar.setFocusPainted(false);
        btCancelar.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 550, 100, 80));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 25)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Alterar Movimentação");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 930, 50));

        lbNome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbNome.setForeground(new java.awt.Color(255, 255, 255));
        lbNome.setText("Cabeleireiro");
        getContentPane().add(lbNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 90, 20));

        txtDataAlteracao.setEditable(false);
        txtDataAlteracao.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtDataAlteracao.setForeground(new java.awt.Color(255, 255, 255));
        txtDataAlteracao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDataAlteracao.setCaretColor(new java.awt.Color(255, 255, 255));
        txtDataAlteracao.setOpaque(false);
        getContentPane().add(txtDataAlteracao, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 150, -1));

        lbDataAlteracao.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbDataAlteracao.setForeground(new java.awt.Color(255, 255, 255));
        lbDataAlteracao.setText("Data Alteracao");
        getContentPane().add(lbDataAlteracao, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 110, 20));

        lbValorTotalVenda.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbValorTotalVenda.setForeground(new java.awt.Color(255, 255, 255));
        lbValorTotalVenda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbValorTotalVenda.setText("Valor Total Venda");
        getContentPane().add(lbValorTotalVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 510, 130, 20));

        txtValorTotalVenda.setEditable(false);
        txtValorTotalVenda.setForeground(new java.awt.Color(255, 255, 255));
        txtValorTotalVenda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtValorTotalVenda.setText("0,0");
        txtValorTotalVenda.setCaretColor(new java.awt.Color(255, 255, 255));
        txtValorTotalVenda.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtValorTotalVenda.setOpaque(false);
        txtValorTotalVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorTotalVendaActionPerformed(evt);
            }
        });
        getContentPane().add(txtValorTotalVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 540, 110, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        btAdicionarProd.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btAdicionarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/adcionar2.png"))); // NOI18N
        btAdicionarProd.setText("Adicionar");
        btAdicionarProd.setBorderPainted(false);
        btAdicionarProd.setContentAreaFilled(false);
        btAdicionarProd.setFocusPainted(false);
        btAdicionarProd.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btAdicionarProd.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btAdicionarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarProdActionPerformed(evt);
            }
        });
        jPanel1.add(btAdicionarProd);
        btAdicionarProd.setBounds(-10, 30, 100, 30);

        btRemoverProd.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btRemoverProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/remover.png"))); // NOI18N
        btRemoverProd.setText("Remover");
        btRemoverProd.setBorderPainted(false);
        btRemoverProd.setContentAreaFilled(false);
        btRemoverProd.setFocusPainted(false);
        btRemoverProd.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btRemoverProd.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btRemoverProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverProdActionPerformed(evt);
            }
        });
        jPanel1.add(btRemoverProd);
        btRemoverProd.setBounds(-10, 97, 100, 23);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ações");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 4, 80, 20);

        btAlterar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/editar2.png"))); // NOI18N
        btAlterar.setText("Alterar");
        btAlterar.setBorderPainted(false);
        btAlterar.setContentAreaFilled(false);
        btAlterar.setFocusPainted(false);
        btAlterar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btAlterar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });
        jPanel1.add(btAlterar);
        btAlterar.setBounds(-10, 60, 90, 30);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 80, 260));

        grid.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descrição", "Quantidade", "Valor Unitario", "Valor Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grid.setShowHorizontalLines(false);
        jScrollPane1.setViewportView(grid);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 650, 260));

        txtCodigoCliente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtCodigoCliente.setForeground(new java.awt.Color(255, 255, 255));
        txtCodigoCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodigoCliente.setCaretColor(new java.awt.Color(255, 255, 255));
        txtCodigoCliente.setOpaque(false);
        txtCodigoCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodigoClienteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodigoClienteFocusLost(evt);
            }
        });
        txtCodigoCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoClienteKeyPressed(evt);
            }
        });
        getContentPane().add(txtCodigoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 50, -1));

        lbNome1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbNome1.setForeground(new java.awt.Color(255, 255, 255));
        lbNome1.setText("Cliente");
        getContentPane().add(lbNome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 50, -1));

        cbFuncionario.setBackground(new java.awt.Color(0, 0, 0));
        cbFuncionario.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cbFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        cbFuncionario.setLightWeightPopupEnabled(false);
        cbFuncionario.setOpaque(false);
        cbFuncionario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbFuncionarioItemStateChanged(evt);
            }
        });
        cbFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(cbFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 170, 150, -1));

        txtCodigoFuncionario.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtCodigoFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        txtCodigoFuncionario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodigoFuncionario.setCaretColor(new java.awt.Color(255, 255, 255));
        txtCodigoFuncionario.setOpaque(false);
        txtCodigoFuncionario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodigoFuncionarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodigoFuncionarioFocusLost(evt);
            }
        });
        txtCodigoFuncionario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoFuncionarioKeyPressed(evt);
            }
        });
        getContentPane().add(txtCodigoFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, 40, -1));

        lbcodigo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbcodigo.setForeground(new java.awt.Color(255, 255, 255));
        lbcodigo.setText("Codigo");
        getContentPane().add(lbcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 50, -1));

        cod_movimentacao.setEditable(false);
        cod_movimentacao.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cod_movimentacao.setForeground(new java.awt.Color(255, 255, 255));
        cod_movimentacao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cod_movimentacao.setOpaque(false);
        cod_movimentacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cod_movimentacaoActionPerformed(evt);
            }
        });
        getContentPane().add(cod_movimentacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 60, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Data");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 40, 20));

        txtData.setEditable(false);
        txtData.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtData.setForeground(new java.awt.Color(255, 255, 255));
        txtData.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtData.setCaretColor(new java.awt.Color(255, 255, 255));
        txtData.setOpaque(false);
        getContentPane().add(txtData, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 120, 150, -1));

        btSalvarMovimento.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btSalvarMovimento.setForeground(new java.awt.Color(255, 255, 255));
        btSalvarMovimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/botaoefetivar5.png"))); // NOI18N
        btSalvarMovimento.setText(" Efetivar");
        btSalvarMovimento.setBorderPainted(false);
        btSalvarMovimento.setContentAreaFilled(false);
        btSalvarMovimento.setFocusPainted(false);
        btSalvarMovimento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSalvarMovimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarMovimentoActionPerformed(evt);
            }
        });
        getContentPane().add(btSalvarMovimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 550, 100, 80));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/PainelFundo2.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1020, 670));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/FundoTelaInicial.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, -1));

        setSize(new java.awt.Dimension(1020, 675));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbClienteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbClienteItemStateChanged
        String codigoNome = cbCliente.getSelectedItem().toString();
        setCodigoCliente(codigoNome);
    }//GEN-LAST:event_cbClienteItemStateChanged

    private void cbClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbClienteFocusGained

    }//GEN-LAST:event_cbClienteFocusGained

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void txtValorTotalVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorTotalVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorTotalVendaActionPerformed

    private void btAdicionarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarProdActionPerformed
        //BuscarProdutoMovimentacao tela = new BuscarProdutoMovimentacao();
        //tela.setVisible(true);
        PesquisaProduto.setLocationRelativeTo(null);
        PesquisaProduto.setVisible(true);
    }//GEN-LAST:event_btAdicionarProdActionPerformed

    private void btRemoverProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverProdActionPerformed
        try {
            int indice = grid.getSelectedRow();
            listProd.remove(indice);
            carregaGrid();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Selecione o produto que deseja remover !");
        }
    }//GEN-LAST:event_btRemoverProdActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        try {
            Integer indice = grid.getSelectedRow();
            setIndice(indice);
            Integer codigo = Integer.parseInt(String.valueOf(grid.getValueAt(grid.getSelectedRow(), 0)));
            String descricao = String.valueOf(grid.getValueAt(grid.getSelectedRow(), 1));
            Integer qtde = Integer.parseInt(String.valueOf(grid.getValueAt(grid.getSelectedRow(), 2)));
            Double valor = Double.valueOf(String.valueOf(grid.getValueAt(grid.getSelectedRow(), 3)).replace(",", ".").replace("R$", ""));
            Double total = Double.valueOf(String.valueOf(grid.getValueAt(grid.getSelectedRow(), 4)).replace(",", "."));

            txtCodigoAltProd.setText(String.valueOf(codigo));
            txtDescricaoAltProd.setText(descricao);
            txtAltQtde.setText(String.valueOf(qtde));
            setMask();
            txtValorUniAlt.setText(String.format("%.2f", valor));
            txtTotalProdAlt.setText(String.format("%.2f", total));

            AlterarProduto.setModal(true);
            AlterarProduto.setLocationRelativeTo(null);
            AlterarProduto.setVisible(true);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Selecione o registro que deseja alterar !");
        }
    }//GEN-LAST:event_btAlterarActionPerformed

    private void txtCodigoClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoClienteFocusGained
        codigoAtualCliente = txtCodigoCliente.getText();
    }//GEN-LAST:event_txtCodigoClienteFocusGained

    private void txtCodigoClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoClienteFocusLost
        //String codigoAtual=cod_movimentacao.getText();
        List<Client> listagem = listCliente;
        String cod = txtCodigoCliente.getText();

        for (Client cb : listagem) {
            if (cod.equals(String.valueOf(cb.getCodigo()))) {
                cbCliente.setSelectedItem(cb.getCodigo() + " | " + cb.getNome());
            }
        }
        String[] codigoFormat = String.valueOf(cbCliente.getSelectedItem().toString()).split(" ");
        if (!codigoFormat[0].equals(cod)) {
            JOptionPane.showMessageDialog(null, "Codigo não encontrado !");
            txtCodigoCliente.setText(codigoAtualCliente);
        }

    }//GEN-LAST:event_txtCodigoClienteFocusLost

    private void txtCodigoClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoClienteKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            cbCliente.requestFocus();
        }
    }//GEN-LAST:event_txtCodigoClienteKeyPressed

    private void cbFuncionarioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbFuncionarioItemStateChanged
        String codigoNome = cbFuncionario.getSelectedItem().toString();
        setCodigoFuncionario(codigoNome);
    }//GEN-LAST:event_cbFuncionarioItemStateChanged

    private void cbFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFuncionarioActionPerformed

    private void txtCodigoFuncionarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoFuncionarioFocusGained
        codigoAtualFuncionario = txtCodigoFuncionario.getText();
    }//GEN-LAST:event_txtCodigoFuncionarioFocusGained

    private void txtCodigoFuncionarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoFuncionarioFocusLost
        List<Employee> listagem = listFuncionario;
        String cod = txtCodigoFuncionario.getText();

        for (Employee cb : listagem) {
            if (cod.equals(String.valueOf(cb.getCodigo()))) {
                cbFuncionario.setSelectedItem(cb.getCodigo() + " | " + cb.getNome());
            }
        }
        String[] codigoFormat = String.valueOf(cbFuncionario.getSelectedItem().toString()).split(" ");
        if (!codigoFormat[0].equals(cod)) {
            JOptionPane.showMessageDialog(null, "Codigo não encontrado !");
            txtCodigoFuncionario.setText(codigoAtualFuncionario);
        }
    }//GEN-LAST:event_txtCodigoFuncionarioFocusLost

    private void txtCodigoFuncionarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoFuncionarioKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            cbFuncionario.requestFocus();
        }
    }//GEN-LAST:event_txtCodigoFuncionarioKeyPressed

    private void cod_movimentacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cod_movimentacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cod_movimentacaoActionPerformed

    private void btSalvarMovimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarMovimentoActionPerformed
        try {
            if (listProd.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Insira pelo menos 1 serviço !");
            } else {
                Integer codigoMovimentacao = Integer.parseInt(cod_movimentacao.getText());
                String dataCadastro = txtData.getText();
                Integer codCliente = Integer.parseInt(txtCodigoCliente.getText());
                Integer codFuncionario = Integer.parseInt(txtCodigoFuncionario.getText());
                Double totalVenda = nf(txtValorTotalVenda.getText()).doubleValue();
                String dataAlteracao = util.data.formatDateToEUA(util.data.getdata());
                
                Client cliente = new Client();
                cliente.setCodigo(codCliente);
                Employee funcionario = new Employee();
                funcionario.setCodigo(codFuncionario);
                Order mov = new Order(codigoMovimentacao, dataCadastro, dataAlteracao, totalVenda, listProd);
                mov.setClient(cliente);
                mov.setEmployee(funcionario);
                OrderService.update(mov, codigoMovimentacao);
                this.dispose();
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btSalvarMovimentoActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        String codigo = txtCodigoBusca.getText().equals("") ? "0" : txtCodigoBusca.getText();
        String Descricao = txtDescricao.getText();
        List<Product> servico = ProductService.findAll(codigo, Descricao, "F", "0");

        DefaultTableModel modelo = (DefaultTableModel) gridBusca.getModel();
        modelo.setNumRows(0);
        TableColumnModel modeltable2 = gridBusca.getColumnModel();
        modeltable2.getColumn(0).setPreferredWidth(45);
        modeltable2.getColumn(1).setPreferredWidth(200);
        modeltable2.getColumn(2).setPreferredWidth(80);

        centralizar(gridBusca, 0);
        centralizar(gridBusca, 1);
        centralizar(gridBusca, 2);

        try {
            String lenlist = String.valueOf(servico.size());
            for (Product mov : servico) {
                modelo.addRow(new Object[]{String.valueOf(mov.getCodigo()), mov.getDescricao(), String.format("%.2f", mov.getPreco())});
            }
            if (lenlist.equals("1")) {
                lbQtdeResult.setText("A pesquisa retornou " + lenlist + " registro");
            } else {
                lbQtdeResult.setText("A pesquisa retornou " + lenlist + " registros");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao buscar os produtos, contate o suporte técnico");
        }
    }//GEN-LAST:event_btBuscarActionPerformed

    private void txtDescricaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescricaoFocusLost
        String minuscula = txtDescricao.getText();
        txtDescricao.setText(minuscula.toUpperCase());
    }//GEN-LAST:event_txtDescricaoFocusLost

    private void txtDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoActionPerformed

    private void txtCodigoBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoBuscaActionPerformed

    private void gridBuscaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gridBuscaMouseClicked
        if (evt.getClickCount() == 2) {
            int codigo = Integer.parseInt(String.valueOf(gridBusca.getValueAt(gridBusca.getSelectedRow(), 0)));
            String descricao = String.valueOf(gridBusca.getValueAt(gridBusca.getSelectedRow(), 1));
            Double valor = Double.valueOf(String.valueOf(gridBusca.getValueAt(gridBusca.getSelectedRow(), 2)).replace(",", "."));
            Product servico = new Product();
            servico.setCodigo(codigo);
            servico.setDescricao(descricao);
            servico.setPreco(valor);
            IncluirProduto.setLocationRelativeTo(null);
            valorUnitario = servico.getPreco();
            txtCodigoProd.setText(String.valueOf(servico.getCodigo()));
            txtDescricaoProd.setText(servico.getDescricao());
            setMask();
            txtValorUni.setText(String.format("%.2f", valorUnitario));
            calculaTotal();
            IncluirProduto.setVisible(true);
        }
    }//GEN-LAST:event_gridBuscaMouseClicked

    private void btCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelar1ActionPerformed
        PesquisaProduto.setVisible(false);
    }//GEN-LAST:event_btCancelar1ActionPerformed

    private void btIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIncluirActionPerformed
        try {
            int codigo = Integer.parseInt(String.valueOf(gridBusca.getValueAt(gridBusca.getSelectedRow(), 0)));
            String descricao = String.valueOf(gridBusca.getValueAt(gridBusca.getSelectedRow(), 1));
            double valor = Double.valueOf(String.valueOf(gridBusca.getValueAt(gridBusca.getSelectedRow(), 2)).replace(",", "."));
            Product servico = new Product();
            servico.setCodigo(codigo);
            servico.setDescricao(descricao);
            servico.setPreco(valor);
            IncluirProduto.setLocationRelativeTo(null);
            valorUnitario = servico.getPreco();
            txtCodigoProd.setText(String.valueOf(servico.getCodigo()));
            txtDescricaoProd.setText(servico.getDescricao());
            setMask();
            txtValorUni.setText(String.format("%.2f", valorUnitario));
            calculaTotal();
            IncluirProduto.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Selecione o servico que deseja incluir");
        }
    }//GEN-LAST:event_btIncluirActionPerformed

    private void txtQtdeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQtdeFocusLost
        calculaTotal();
    }//GEN-LAST:event_txtQtdeFocusLost

    private void txtQtdeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtdeKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            txtCodigoProd.requestFocus();
        }
    }//GEN-LAST:event_txtQtdeKeyPressed

    private void txtValorUniFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorUniFocusLost
        calculaTotal();
    }//GEN-LAST:event_txtValorUniFocusLost

    private void txtValorUniKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorUniKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            txtCodigoProd.requestFocus();
        }
    }//GEN-LAST:event_txtValorUniKeyPressed

    private void btEfetivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEfetivarActionPerformed
        try {
            int codigo;
            codigo = Integer.parseInt(txtCodigoProd.getText());
            int qtde = Integer.parseInt(txtQtde.getText());
            double valorUnitario = nf(txtValorUni.getText()).doubleValue();
            double valorTotal = nf(txtTotalProd.getText()).doubleValue();

            Product servico = new Product(codigo, txtDescricaoProd.getText(), 0.0, "", "", "", "", "");
            OrderItem incluir = new OrderItem(servico, qtde, valorUnitario);
            listProd.add(incluir);
            listProduto = listProd;
            carregaGrid();
            //incluir.setListaProduto(incluir);
            txtQtde.setText("1");
            IncluirProduto.setVisible(false);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao adicionar Produto!");
        }
    }//GEN-LAST:event_btEfetivarActionPerformed

    private void btCancelarIncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarIncActionPerformed
        IncluirProduto.setVisible(false);
    }//GEN-LAST:event_btCancelarIncActionPerformed

    private void txtTotalProdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTotalProdFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalProdFocusLost

    private void txtAltQtdeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAltQtdeFocusLost
        calculaTotalAlt();
    }//GEN-LAST:event_txtAltQtdeFocusLost

    private void txtValorUniAltFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorUniAltFocusLost
        calculaTotalAlt();
    }//GEN-LAST:event_txtValorUniAltFocusLost

    private void btEfetivarAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEfetivarAltActionPerformed
        try {
            int indice = getIndice();
            listProd.remove(indice);

            int codigo;
            codigo = Integer.parseInt(txtCodigoAltProd.getText());
            int qtde = Integer.parseInt(txtAltQtde.getText());
            double valorUnitario = nf(txtValorUniAlt.getText()).doubleValue();
            double valorTotal = nf(txtTotalProdAlt.getText()).doubleValue();

            Product servico = new Product(codigo, txtDescricaoAltProd.getText(), 0.0, "", "", "", "", "");
            OrderItem incluir = new OrderItem(servico, qtde, valorUnitario);
            listProd.add(indice, incluir);
            listProduto = listProd;
            carregaGrid();
            AlterarProduto.setVisible(false);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao alterar produto !");
        }
    }//GEN-LAST:event_btEfetivarAltActionPerformed

    private void btCancelarAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarAltActionPerformed
        AlterarProduto.setVisible(false);
    }//GEN-LAST:event_btCancelarAltActionPerformed

    private void txtTotalProdAltFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTotalProdAltFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalProdAltFocusLost

    private void btPesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarClienteActionPerformed
        PesquisarCliente.setLocationRelativeTo(null);
        PesquisarCliente.setModal(true);
        PesquisarCliente.setVisible(true);
    }//GEN-LAST:event_btPesquisarClienteActionPerformed

    private void btLimparBuscaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparBuscaClienteActionPerformed
        txtBuscaCPFCliente.setFormatterFactory(Mascara.cleanMak());
        txtBuscaRGCliente.setFormatterFactory(Mascara.cleanMak());
        txtBuscaCodigoCliente.setText("");
        txtBuscaNomeCliente.setText("");
    }//GEN-LAST:event_btLimparBuscaClienteActionPerformed

    private void txtBuscaRGClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscaRGClienteFocusGained
        txtBuscaRGCliente.setFormatterFactory(Mascara.getRgMask());
    }//GEN-LAST:event_txtBuscaRGClienteFocusGained

    private void txtBuscaRGClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaRGClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscaRGClienteActionPerformed

    private void btBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscar1ActionPerformed
        String codigo = txtBuscaCodigoCliente.getText().equals("") ? "0" : txtBuscaCodigoCliente.getText();
        String nome = txtBuscaNomeCliente.getText();
        String cpf = txtBuscaCPFCliente.getText();
        String rg = txtBuscaRGCliente.getText();

        List<Client> cliente = ClientService.findAll(codigo, nome, cpf, rg, "", "0");

        DefaultTableModel modelo = (DefaultTableModel) gridBuscaCliente.getModel();
        modelo.setNumRows(0);
        TableColumnModel modeltable2 = gridBuscaCliente.getColumnModel();
        modeltable2.getColumn(0).setPreferredWidth(45);
        modeltable2.getColumn(1).setPreferredWidth(170);
        modeltable2.getColumn(2).setPreferredWidth(100);
        modeltable2.getColumn(3).setPreferredWidth(100);
        modeltable2.getColumn(4).setPreferredWidth(5);

        centralizar(gridBuscaCliente, 0);
        centralizar(gridBuscaCliente, 1);
        centralizar(gridBuscaCliente, 2);
        centralizar(gridBuscaCliente, 3);

        try {
            String lenlist;
            lenlist = String.valueOf(cliente.size());
            for (Client cli : cliente) {
                modelo.addRow(new Object[]{String.valueOf(cli.getCodigo()), cli.getNome(), cli.getCpf(), cli.getRg()});
            }
            if (lenlist.equals("1")) {
                lbQtdeResultCliente.setText(lenlist + " registro");
            } else {
                lbQtdeResultCliente.setText(lenlist + " registros");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btBuscar1ActionPerformed

    private void txtBuscaNomeClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscaNomeClienteFocusLost
        String minuscula = txtBuscaNomeCliente.getText();
        txtBuscaNomeCliente.setText(minuscula.toUpperCase());
    }//GEN-LAST:event_txtBuscaNomeClienteFocusLost

    private void txtBuscaNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaNomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscaNomeClienteActionPerformed

    private void txtBuscaCPFClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscaCPFClienteFocusGained
        txtBuscaCPFCliente.setFormatterFactory(Mascara.getCpfMask());
    }//GEN-LAST:event_txtBuscaCPFClienteFocusGained

    private void txtBuscaCodigoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaCodigoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscaCodigoClienteActionPerformed

    private void gridBuscaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gridBuscaClienteMouseClicked
        if (evt.getClickCount() == 2) {
            String codigo = String.valueOf(gridBuscaCliente.getValueAt(gridBuscaCliente.getSelectedRow(), 0));
            String nome = String.valueOf(gridBuscaCliente.getValueAt(gridBuscaCliente.getSelectedRow(), 1));
            int codigoformat = Integer.parseInt(codigo);
            cbCliente.setSelectedItem(codigo + " | " + nome);
            PesquisarCliente.dispose();
        }
    }//GEN-LAST:event_gridBuscaClienteMouseClicked

    private void btCancelar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelar2ActionPerformed
        PesquisarCliente.dispose();
    }//GEN-LAST:event_btCancelar2ActionPerformed

    private void btBuscaEscolherClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscaEscolherClienteActionPerformed
        String codigo = gridBuscaCliente.getValueAt(gridBuscaCliente.getSelectedRow(), 0).toString();
        String nome = gridBuscaCliente.getValueAt(gridBuscaCliente.getSelectedRow(), 1).toString();
        cbCliente.setSelectedItem(codigo + " | " + nome);
        PesquisarCliente.dispose();
    }//GEN-LAST:event_btBuscaEscolherClienteActionPerformed

    private static void centralizar(JTable table, int column) {
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        table.getColumnModel().getColumn(column).setCellRenderer(centerRenderer);
    }

    public void carregaGrid() {
        DefaultTableModel modelo = (DefaultTableModel) grid.getModel();
        modelo.setNumRows(0);

        centralizar(grid, 0);
        centralizar(grid, 1);
        centralizar(grid, 2);
        centralizar(grid, 3);
        centralizar(grid, 4);
        double valorTotalVenda = 0;
        try {
            List<OrderItem> listagem = listProd;
            for (OrderItem mov : listagem) {
                String codigoformat;
                String valorFormat;
                String totalFormat;
                codigoformat = String.valueOf(mov.getProduct().getCodigo());
                valorFormat = String.format("%.2f", mov.getPrice());
                totalFormat = String.format("%.2f", mov.getPrice() * mov.getQuantity());
                modelo.addRow(new Object[]{codigoformat, mov.getProduct().getDescricao(), mov.getQuantity(), valorFormat, totalFormat});

                valorTotalVenda = valorTotalVenda + Double.parseDouble(totalFormat.replace(",", "."));
            }
            txtValorTotalVenda.setText(String.format("%.2f", valorTotalVenda));
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void setMask() {
        txtValorUni.setFormatterFactory(Mascara.getValorMask());
        txtTotalProd.setFormatterFactory(Mascara.getValorMask());
        txtValorUniAlt.setFormatterFactory(Mascara.getValorMask());
        txtTotalProdAlt.setFormatterFactory(Mascara.getValorMask());
    }

    private void calculaTotal() {
        int qtde = Integer.valueOf(txtQtde.getText());
        double total;
        try {
            valorUnitario = nf(txtValorUni.getText()).doubleValue();
        } catch (ParseException ex) {
            Logger.getLogger(IncluirMovimento.class.getName()).log(Level.SEVERE, null, ex);
        }
        total = valorUnitario * qtde;
        txtTotalProd.setText(String.format("%.2f", total));
    }

    private void calculaTotalAlt() {
        int qtde = Integer.valueOf(txtAltQtde.getText());
        double total;
        try {
            valorUnitario = nf(txtValorUniAlt.getText()).doubleValue();
        } catch (ParseException ex) {
            Logger.getLogger(IncluirMovimento.class.getName()).log(Level.SEVERE, null, ex);
        }
        total = valorUnitario * qtde;
        txtTotalProdAlt.setText(String.format("%.2f", total));
    }

    private void setIndice(int indice) {
        this.indice = indice;
    }

    private int getIndice() {
        return indice;
    }

    private void setValue() {
        try {
            cod_movimentacao.setText(codigo);
            //Pega os valores da movimentacao e insere nos respectivos campos
            Order selectAlteraMovimento = OrderService.findById(codigo);

            txtData.setText(util.data.formataDataBD(String.valueOf(selectAlteraMovimento.getDataCadastro())));
            txtDataAlteracao.setText(data.formataDataBD(String.valueOf(selectAlteraMovimento.getDataAlteracao())));
            String cliente = String.valueOf(selectAlteraMovimento.getClient().getCodigo()) + " | " + selectAlteraMovimento.getClient().getNome();
            String funcionario = String.valueOf(selectAlteraMovimento.getEmployee().getCodigo()) + " | " + selectAlteraMovimento.getEmployee().getNome();
            listProd = selectAlteraMovimento.getItems();
            setOpcoesCBCliente();
            setOpcoesCBFuncionario();
            cbCliente.setSelectedItem(cliente);
            cbFuncionario.setSelectedItem(funcionario);

            carregaGrid();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void setOpcoesCBCliente() {
        List<Client> cliente = ClientService.findAll("0", "", "", "", "", "");
        String codigoNome = null;
        listCliente = cliente;
        try {
            for (Client cli : cliente) {
                codigoNome = String.valueOf(cli.getCodigo()) + " | " + cli.getNome();
                cbCliente.addItem(codigoNome);
            }
            codigoNome = cbCliente.getSelectedItem().toString();
            setCodigoCliente(codigoNome);
        } catch (java.lang.NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Cadastre pelo menos 1 cliente para realizar movimentações");
            this.dispose();
            e.printStackTrace();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void setOpcoesCBFuncionario() {
        List<Employee> funcionario = EmployeeService.findAll("0", "", "", "", "", "0");
        this.listFuncionario = funcionario;
        String codigoNome = null;
        try {
            for (Employee func : funcionario) {
                codigoNome = String.valueOf(func.getCodigo()) + " | " + func.getNome();
                cbFuncionario.addItem(codigoNome);
            }
            codigoNome = cbFuncionario.getSelectedItem().toString();
            setCodigoFuncionario(codigoNome);
        } catch (java.lang.NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Cadastre pelo menos 1 funcionario para realizar movimentações");
            this.dispose();
            e.printStackTrace();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void setCodigoFuncionario(String codigoNome) {
        String[] codigoFormat2 = codigoNome.split(" ");
        txtCodigoFuncionario.setText(codigoFormat2[0]);
    }

    private void setCodigoCliente(String codigoNome) {
        String[] codigoFormat = codigoNome.split(" ");
        txtCodigoCliente.setText(codigoFormat[0]);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarMovimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarMovimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarMovimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarMovimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarMovimento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog AlterarProduto;
    private javax.swing.JDialog IncluirProduto;
    private javax.swing.JDialog PesquisaProduto;
    private javax.swing.JDialog PesquisarCliente;
    private javax.swing.JButton btAdicionarProd;
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btBuscaEscolherCliente;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btBuscar1;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btCancelar1;
    private javax.swing.JButton btCancelar2;
    private javax.swing.JButton btCancelarAlt;
    private javax.swing.JButton btCancelarInc;
    private javax.swing.JButton btEfetivar;
    private javax.swing.JButton btEfetivarAlt;
    private javax.swing.JButton btIncluir;
    private javax.swing.JButton btLimparBuscaCliente;
    private javax.swing.JButton btPesquisarCliente;
    private javax.swing.JButton btRemoverProd;
    private javax.swing.JButton btSalvarMovimento;
    private javax.swing.JComboBox<String> cbCliente;
    private javax.swing.JComboBox<String> cbFuncionario;
    private javax.swing.JTextField cod_movimentacao;
    private javax.swing.JTable grid;
    private javax.swing.JTable gridBusca;
    private javax.swing.JTable gridBuscaCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbCPF;
    private javax.swing.JLabel lbCPF1;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbCodigo1;
    private javax.swing.JLabel lbCodigo2;
    private javax.swing.JLabel lbCodigo3;
    private javax.swing.JLabel lbDataAlteracao;
    private javax.swing.JLabel lbDescricao;
    private javax.swing.JLabel lbDescricao1;
    private javax.swing.JLabel lbDescricao2;
    private javax.swing.JLabel lbDescricao3;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbNome1;
    private javax.swing.JLabel lbQtde;
    private javax.swing.JLabel lbQtde1;
    private javax.swing.JLabel lbQtdeResult;
    private javax.swing.JLabel lbQtdeResultCliente;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbTitulo1;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JLabel lbTotal1;
    private javax.swing.JLabel lbValor;
    private javax.swing.JLabel lbValor1;
    private javax.swing.JLabel lbValorTotalVenda;
    private javax.swing.JLabel lbcodigo;
    private javax.swing.JTextField txtAltQtde;
    private javax.swing.JFormattedTextField txtBuscaCPFCliente;
    private javax.swing.JTextField txtBuscaCodigoCliente;
    private javax.swing.JTextField txtBuscaNomeCliente;
    private javax.swing.JFormattedTextField txtBuscaRGCliente;
    private javax.swing.JTextField txtCodigoAltProd;
    private javax.swing.JTextField txtCodigoBusca;
    private javax.swing.JTextField txtCodigoCliente;
    private javax.swing.JTextField txtCodigoFuncionario;
    private javax.swing.JTextField txtCodigoProd;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtDataAlteracao;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtDescricaoAltProd;
    private javax.swing.JTextField txtDescricaoProd;
    private javax.swing.JTextField txtQtde;
    private javax.swing.JFormattedTextField txtTotalProd;
    private javax.swing.JFormattedTextField txtTotalProdAlt;
    private javax.swing.JFormattedTextField txtValorTotalVenda;
    private javax.swing.JFormattedTextField txtValorUni;
    private javax.swing.JFormattedTextField txtValorUniAlt;
    // End of variables declaration//GEN-END:variables
}
