/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Movimentacao;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.NumberFormat;
import java.util.List;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import model.Order;
import model.User;
import service.OrderService;
import util.Mascara;
import util.ValidaNumeros;
import util.data;
import static util.data.formatDateToEUA;
import static util.data.getdata;

/**
 *
 * @author Jonas Santos
 */
public class MovimentacaoPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MovimentacaoPrincipal
     */
    User user;
    
    public MovimentacaoPrincipal(User usuario) {
        initComponents();
        txtDataInicial.setFormatterFactory(Mascara.getDataMask());
        txtDataFinal.setFormatterFactory(Mascara.getDataMask());
        user = usuario;
        TableColumnModel modeltable = grid.getColumnModel();
        modeltable.getColumn(0).setPreferredWidth(80);
        modeltable.getColumn(1).setPreferredWidth(80);
        modeltable.getColumn(2).setPreferredWidth(200);
        modeltable.getColumn(3).setPreferredWidth(110);
        modeltable.getColumn(4).setPreferredWidth(150);
        modeltable.getColumn(5).setPreferredWidth(130);
        modeltable.getColumn(6).setPreferredWidth(140);
        modeltable.getColumn(7).setPreferredWidth(80);
        modeltable.getColumn(8).setPreferredWidth(120);
        txtCodigoMovimentacao.setDocument(new ValidaNumeros());
        txtCodigoCliente.setDocument(new ValidaNumeros());
        setDate();
    }
    
    private MovimentacaoPrincipal() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitulo = new javax.swing.JLabel();
        lbCodigo1 = new javax.swing.JLabel();
        lbCodigo2 = new javax.swing.JLabel();
        lbCodigo3 = new javax.swing.JLabel();
        lbCodigo4 = new javax.swing.JLabel();
        lbCodigo5 = new javax.swing.JLabel();
        lbLenlist = new javax.swing.JLabel();
        txtDataInicial = new javax.swing.JFormattedTextField();
        txtLimite = new javax.swing.JTextField();
        lbCodigo7 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCodigoCliente = new javax.swing.JTextField();
        txtDataFinal = new javax.swing.JFormattedTextField();
        lbCodigo8 = new javax.swing.JLabel();
        btAlterar = new javax.swing.JButton();
        btIncluir = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        grid = new javax.swing.JTable();
        lbCodigoMovimentacao = new javax.swing.JLabel();
        txtCodigoMovimentacao = new javax.swing.JTextField();
        txtCPF = new javax.swing.JFormattedTextField();
        txtRG = new javax.swing.JFormattedTextField();
        btLimpar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbPainelBotoes = new javax.swing.JLabel();
        lbmenu = new javax.swing.JLabel();
        lbfundo = new javax.swing.JLabel();
        lbimagem = new javax.swing.JLabel();
        lbimagem1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTitulo.setBackground(new java.awt.Color(0, 0, 0));
        lbTitulo.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo.setText("Movimentação");
        lbTitulo.setOpaque(true);
        getContentPane().add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 690, 50));

        lbCodigo1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lbCodigo1.setForeground(new java.awt.Color(255, 255, 255));
        lbCodigo1.setText("CPF");
        getContentPane().add(lbCodigo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, 20));

        lbCodigo2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lbCodigo2.setForeground(new java.awt.Color(255, 255, 255));
        lbCodigo2.setText("RG");
        getContentPane().add(lbCodigo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, 40));

        lbCodigo3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lbCodigo3.setForeground(new java.awt.Color(255, 255, 255));
        lbCodigo3.setText("Cliente");
        getContentPane().add(lbCodigo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        lbCodigo4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lbCodigo4.setForeground(new java.awt.Color(255, 255, 255));
        lbCodigo4.setText("Limite");
        getContentPane().add(lbCodigo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, -1, -1));

        lbCodigo5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lbCodigo5.setForeground(new java.awt.Color(255, 255, 255));
        lbCodigo5.setText("Data Inicial");
        getContentPane().add(lbCodigo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, 30));

        lbLenlist.setForeground(new java.awt.Color(255, 255, 255));
        lbLenlist.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbLenlist, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, 220, 30));
        getContentPane().add(txtDataInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 220, -1));

        txtLimite.setText("500");
        getContentPane().add(txtLimite, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, 220, -1));

        lbCodigo7.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lbCodigo7.setForeground(new java.awt.Color(255, 255, 255));
        lbCodigo7.setText("Data Final");
        getContentPane().add(lbCodigo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, 30));
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 220, -1));
        getContentPane().add(txtCodigoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 220, -1));
        getContentPane().add(txtDataFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 220, -1));

        lbCodigo8.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lbCodigo8.setForeground(new java.awt.Color(255, 255, 255));
        lbCodigo8.setText("Cod. Cliente");
        getContentPane().add(lbCodigo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        btAlterar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btAlterar.setForeground(new java.awt.Color(255, 255, 255));
        btAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/botaoefetivar5.png"))); // NOI18N
        btAlterar.setText("Alterar");
        btAlterar.setToolTipText("");
        btAlterar.setBorderPainted(false);
        btAlterar.setContentAreaFilled(false);
        btAlterar.setFocusPainted(false);
        btAlterar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 550, 140, 50));

        btIncluir.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btIncluir.setForeground(new java.awt.Color(255, 255, 255));
        btIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/botaoefetivar5.png"))); // NOI18N
        btIncluir.setText("Incluir");
        btIncluir.setToolTipText("");
        btIncluir.setBorderPainted(false);
        btIncluir.setContentAreaFilled(false);
        btIncluir.setFocusPainted(false);
        btIncluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIncluirActionPerformed(evt);
            }
        });
        getContentPane().add(btIncluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 550, 140, 50));

        btCancelar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/botaocancelar6.png"))); // NOI18N
        btCancelar.setText("Fechar");
        btCancelar.setToolTipText("");
        btCancelar.setBorderPainted(false);
        btCancelar.setContentAreaFilled(false);
        btCancelar.setFocusPainted(false);
        btCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 550, 140, 50));

        btExcluir.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/botaocancelar6.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.setToolTipText("");
        btExcluir.setBorderPainted(false);
        btExcluir.setContentAreaFilled(false);
        btExcluir.setFocusPainted(false);
        btExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 550, 140, 50));

        btPesquisar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/botaoefetivar5.png"))); // NOI18N
        btPesquisar.setText("Pesquisar");
        btPesquisar.setToolTipText("");
        btPesquisar.setBorderPainted(false);
        btPesquisar.setContentAreaFilled(false);
        btPesquisar.setFocusPainted(false);
        btPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 550, 140, 50));

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jScrollPane1.setOpaque(false);

        grid.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        grid.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Movimentação", "Cod.Cliente", "Cliente", "Valor Total", "CPF", "RG", "Data Movimentação", "Cod.Funcionario", "Funcionario", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grid.setToolTipText("");
        grid.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        grid.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        grid.setGridColor(new java.awt.Color(239, 239, 239));
        grid.setName(""); // NOI18N
        grid.setSelectionBackground(new java.awt.Color(216, 216, 216));
        grid.setSelectionForeground(new java.awt.Color(61, 61, 61));
        grid.setShowHorizontalLines(false);
        grid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gridMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(grid);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 690, 440));

        lbCodigoMovimentacao.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lbCodigoMovimentacao.setForeground(new java.awt.Color(255, 255, 255));
        lbCodigoMovimentacao.setText("Cod. Movimentacao");
        getContentPane().add(lbCodigoMovimentacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));
        getContentPane().add(txtCodigoMovimentacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 220, -1));

        txtCPF.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtCPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCPFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCPFFocusLost(evt);
            }
        });
        getContentPane().add(txtCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 220, -1));

        txtRG.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRGFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRGFocusLost(evt);
            }
        });
        getContentPane().add(txtRG, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 220, -1));

        btLimpar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btLimpar.setForeground(new java.awt.Color(255, 255, 255));
        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/botaoefetivar5.png"))); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.setToolTipText("");
        btLimpar.setBorderPainted(false);
        btLimpar.setContentAreaFilled(false);
        btLimpar.setFocusPainted(false);
        btLimpar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 280, 60));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Filtros");
        jLabel1.setMaximumSize(new java.awt.Dimension(58, 30));
        jLabel1.setMinimumSize(new java.awt.Dimension(58, 30));
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(58, 30));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 279, 50));

        lbPainelBotoes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPainelBotoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ClientePrincipal_fundo.png"))); // NOI18N
        lbPainelBotoes.setToolTipText("");
        getContentPane().add(lbPainelBotoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 550, 670, 50));

        lbmenu.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        lbmenu.setForeground(new java.awt.Color(255, 255, 255));
        lbmenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/menuClientePrincipal_fundo.png"))); // NOI18N
        lbmenu.setText("Filtros");
        getContentPane().add(lbmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 300, 580));

        lbfundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbfundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ClientePrincipal_fundo.png"))); // NOI18N
        getContentPane().add(lbfundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 690, 540));

        lbimagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbimagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/FundoTelaInicial.jpg"))); // NOI18N
        getContentPane().add(lbimagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, -1));

        lbimagem1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbimagem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/FundoTelaInicial.jpg"))); // NOI18N
        getContentPane().add(lbimagem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, -1));

        setSize(new java.awt.Dimension(1020, 675));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        try {
            Object obj = grid.getValueAt(grid.getSelectedRow(), 0);
            AlterarMovimento alterar = new AlterarMovimento(obj.toString());
            alterar.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Selecione o registro que deseja alterar");
        }
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIncluirActionPerformed
        IncluirMovimento incluir = new IncluirMovimento();
        incluir.setVisible(true);
    }//GEN-LAST:event_btIncluirActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        int codigoMovimentacao = txtCodigoMovimentacao.getText().equals("") ? 0 : Integer.parseInt(txtCodigoMovimentacao.getText());
        int codigoCliente = txtCodigoCliente.getText().equals("") ? 0 : Integer.parseInt(txtCodigoCliente.getText());
        String nome = txtNome.getText();
        String cpf = util.coalesce.coalesceMascara(txtCPF.getText());
        String rg = util.coalesce.coalesceMascara(txtRG.getText());
        String DataInicial = formatDateToEUA(txtDataInicial.getText());
        String DataFinal = formatDateToEUA(txtDataFinal.getText());
        String limite = txtLimite.getText();
        String dataConcatenada = DataInicial + "x" + DataFinal; //O programa sempre irá setar a data inicial e final com a data do dia que esta sendo realizado a consulta
        List<Order> movimentacao = OrderService.findCustom(String.valueOf(codigoMovimentacao), String.valueOf(codigoCliente), nome, cpf, rg, "", dataConcatenada.replace("/", "."), limite);
        
        DefaultTableModel modelo = (DefaultTableModel) grid.getModel();
        modelo.setNumRows(0);
        
        centralizar(grid, 0);
        centralizar(grid, 1);
        centralizar(grid, 2);
        centralizar(grid, 3);
        centralizar(grid, 4);
        centralizar(grid, 5);
        centralizar(grid, 6);
        centralizar(grid, 7);
        centralizar(grid, 8);
        
        try {
            String lenlist;
            lenlist = String.valueOf(movimentacao.size());
            for (Order mov : movimentacao) {
                modelo.addRow(new Object[]{String.valueOf(mov.getCodigo()), mov.getClient().getCodigo(), mov.getClient().getNome(), NumberFormat.getCurrencyInstance().format(mov.getValorTotal()), mov.getClient().getCpf(), mov.getClient().getRg(),
                    util.data.formataDataBD(mov.getDataCadastro()), mov.getEmployee().getCodigo(), mov.getEmployee().getNome()});
            }
            
            if (lenlist.equals("1")) {
                lbLenlist.setText("A pesquisa retornou " + lenlist + " registro");
            } else {
                lbLenlist.setText("A pesquisa retornou " + lenlist + " registros");
            }
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void gridMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gridMouseClicked
        if (evt.getClickCount() == 2) {
            Object obj = grid.getValueAt(grid.getSelectedRow(), 0);
            AlterarMovimento alterar = new AlterarMovimento(obj.toString());
            alterar.setVisible(true);
        }
    }//GEN-LAST:event_gridMouseClicked

    private void txtCPFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCPFFocusGained
        txtCPF.setFormatterFactory(Mascara.getCpfMask());
    }//GEN-LAST:event_txtCPFFocusGained

    private void txtRGFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRGFocusGained
        txtRG.setFormatterFactory(Mascara.getRgMask());
    }//GEN-LAST:event_txtRGFocusGained

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        txtCPF.setText(null);
        txtRG.setText(null);
        txtNome.setText("");
        txtCodigoMovimentacao.setText("");
        txtCodigoCliente.setText("");
        setDate();
        txtLimite.setText("500");
    }//GEN-LAST:event_btLimparActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus

    }//GEN-LAST:event_formWindowGainedFocus

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        try {
            String permissao = user.getGerencia();
            if (permissao.equals("T")) {
                String codMovimentacaoSelecionado = grid.getValueAt(grid.getSelectedRow(), 0).toString();
                String descMovCliente = grid.getValueAt(grid.getSelectedRow(), 2).toString();
                int confirmacao = JOptionPane.showConfirmDialog(null, "Deseja excluir a movimentação selecionada ? \n Movimentação: " + codMovimentacaoSelecionado + " | Cliente: " + descMovCliente, "**** Atenção ****", 1);
                if (confirmacao == 0) {
                    int cod = Integer.parseInt(codMovimentacaoSelecionado);
                    OrderService.delete(cod);
                }
                btPesquisar.doClick();
            } else {
                JOptionPane.showMessageDialog(null, "Usuario não possui privilegio administrativo para realizar esta ação");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Selecione a movimentação que deseja excluir !");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void txtCPFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCPFFocusLost
        txtCPF.setFocusLostBehavior(JFormattedTextField.COMMIT);
    }//GEN-LAST:event_txtCPFFocusLost

    private void txtRGFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRGFocusLost
        txtRG.setFocusLostBehavior(JFormattedTextField.COMMIT);
    }//GEN-LAST:event_txtRGFocusLost
    
    private static void centralizar(JTable table, int column) {
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        table.getColumnModel().getColumn(column).setCellRenderer(centerRenderer);
    }
    
    private void setDate() {
        txtDataInicial.setText(data.getDataMenos1Dia(data.formataDataFiltro(getdata())));
        txtDataFinal.setText(data.formataDataFiltro(getdata()));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovimentacaoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovimentacaoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovimentacaoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovimentacaoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovimentacaoPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btIncluir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JTable grid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCodigo1;
    private javax.swing.JLabel lbCodigo2;
    private javax.swing.JLabel lbCodigo3;
    private javax.swing.JLabel lbCodigo4;
    private javax.swing.JLabel lbCodigo5;
    private javax.swing.JLabel lbCodigo7;
    private javax.swing.JLabel lbCodigo8;
    private javax.swing.JLabel lbCodigoMovimentacao;
    private javax.swing.JLabel lbLenlist;
    private javax.swing.JLabel lbPainelBotoes;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbfundo;
    private javax.swing.JLabel lbimagem;
    private javax.swing.JLabel lbimagem1;
    private javax.swing.JLabel lbmenu;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JTextField txtCodigoCliente;
    private javax.swing.JTextField txtCodigoMovimentacao;
    private javax.swing.JFormattedTextField txtDataFinal;
    private javax.swing.JFormattedTextField txtDataInicial;
    private javax.swing.JTextField txtLimite;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtRG;
    // End of variables declaration//GEN-END:variables
}
